import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";
import QueryProvider from "../Providers/QueryProvider.jsx";
import NextAuthSessionProvider from "../Providers/NextAuthSessionProvider"


// import { usePathname } from "next/navigation";
// import { usePathname } from "next/navigation";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: {
    default: "Khushi's First Next App",
    template: "%s | Khushi's First Next App",
  },
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  // const pathname = usePathname();
  // const hideNav = pathname?.includes("dashboard") || pathname === "/not-found";

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable}   antialiased  `}
        suppressHydrationWarning
      >
        <QueryProvider>
          <NextAuthSessionProvider>
            <Navbar></Navbar>
            <main className="min-h-[calc(100vh-160px)] text-center ">
              {children}
            </main>
            <Footer></Footer>
          </NextAuthSessionProvider>
        </QueryProvider>
      </body>
    </html>
  );
}
